### ISSUE TITLE
Number of HDDs parameter

### ISSUE THREAD

**Issue by thiete** [petersulyok/smfc#23]
This is rather minor, but why does "count" parameter for the HD zone exist? The program will complain if the number of drives listed under hd_names doesn't match this, so clearly it can count the number of drives directly from the hd_names array. Is it intended to be a sanity check for the user?

**Comment by petersulyok** [comment]
Hi @thiete, I understand where you are coming from.

I have two reasons to keep using `count=` parameter for HD zone:

- In order to avoid user misconfiguration this is the primary information about the number of the disk drives. It helps to avoid situation when user wanted to specify 8 disks but only 7 names are given.
- Symmetrical design with CPU zone. In CPU zone this parameter is unavoidable.
